### ISSUE TITLE
访问出现异常，请刷新后重试

### ISSUE THREAD

**Issue by itheochan** [webxmsj/baidu-translate#2]
[vscode-comment-translate](https://github.com/intellism/vscode-comment-translate)来的。`comment-translate`+[baidu translate](https://github.com/webxmsj/baidu-translate)翻译失败：
```
[Start translate]: Use 'Baidu' translate source
[Baidu]: request error:
 [object Object] 
 Try again later or change translate source.{"errno":1022,"errmsg":"访问出现异常，请刷新后重试！","logid": 00000,"error":1022,"errShowMsg":"访问出现异常，请刷新后重试！"}
```

**Comment by bfrontend** [comment]
> [vscode-comment-translate](https://github.com/intellism/vscode-comment-translate)来的。`comment-translate`+[baidu translate](https://github.com/webxmsj/baidu-translate)翻译失败：
> 
> ```
> [Start translate]: Use 'Baidu' translate source
> [Baidu]: request error:
>  [object Object] 
>  Try again later or change translate source.{"errno":1022,"errmsg":"访问出现异常，请刷新后重试！","logid": 00000,"error":1022,"errShowMsg":"访问出现异常，请刷新后重试！"}
> ```

提供id和key了吗

**Comment by bfrontend** [comment]
貌似是文本长度太长导致 能提供下待翻译的文本及从什么语言翻译到什么语言

**Comment by itheochan** [comment]
请关闭这个issue吧。
貌似是误切换到了[vscode-comment-translate](https://github.com/intellism/vscode-comment-translate)内置的`baidu`翻译源。再切换回来又好了。很抱歉造成了误会。

**Comment by itheochan** [comment]
我将关闭这个issue。
貌似是误切换到了[vscode-comment-translate](https://github.com/intellism/vscode-comment-translate)内置的baidu翻译源。再切换回来又好了。很抱歉造成了误会。
